interface IDataTranslate {
	[key: string]: {
		[key: string]: string
	}
}

export const dataTranslate: IDataTranslate = {
	ru: {
		Home: 'Главная',
		Tasks: 'Задачи',
		Timer: 'Таймер',
		'Time blocking': 'Рутина',
		Settings: 'Настройки',
		Statistics: 'Статистика',
		'Total tasks': 'Всего задач',
		'Completed tasks': 'Выполнено задач',
		'Today tasks': 'Задач на сегодня',
		'Week tasks': 'Задач на неделю',
		List: 'Список',
		Kanban: 'Доска',
		Todo: 'Список дел',
		'Task name': 'Название задачи',
		'Due date': 'Срок',
		Priority: 'Приоритет',
		Today: 'Сегодня',
		Tomorrow: 'Завтра',
		'On this week': 'На этой неделе',
		'On next week': 'На следующей неделе',
		Later: 'Позже',
		Completed: 'Выполнено',
		'Add task...': 'Добавить задачу...',
		'Create session': 'Создать сессию',
		Cancel: 'Отмена',
		Start: 'Старт',
		Pause: 'Пауза',
		'Enter name:': 'Введите название:',
		'Enter duration: (min.):': 'Введите продолжительность: (мин.):',
		Color: 'Цвет',
		Create: 'Создать',
		'Total time': 'Общее время',
		hours: 'часов',
		minutes: 'минут',
		'left for sleep': 'осталось для сна',
		Security: 'Безопасность',
		Appearance: 'Внешний вид',
		'With love from': 'С любовью от',
		'All rights reserved': 'Все права защищены',
		Name: 'Имя',
		Mail: 'Почта',
		Password: 'Пароль',
		'Enter new name': 'Введите новое имя',
		'Enter new mail': 'Введите новую почту',
		'Enter new password': 'Введите новый пароль',
		Save: 'Сохранить',
		'Work interval (min.):': 'Интервал работы (мин.):',
		'Break interval (min.):': 'Интервал перерыва (мин.):',
		'Intervals count (max 10):': 'Количество интервалов (макс 10):',
		'Enter work interval:': 'Введите интервал работы:',
		'Enter break interval:': 'Введите интервал перерыва:',
		'Enter intervals count:': 'Введите количество интервалов:',
		'Dark theme': 'Темная тема',
		Language: 'Язык',
		'Add the first time block on the right form':
			'Добавьте первый временной блок в правой форме',
		Update: 'Обновить'
	},
	en: {
		Home: 'Home',
		Tasks: 'Tasks',
		Timer: 'Timer',
		'Time blocking': 'Time blocking',
		Settings: 'Settings',
		Statistics: 'Statistics',
		'Total tasks': 'Total tasks',
		'Completed tasks': 'Completed tasks',
		'Today tasks': 'Today tasks',
		'Week tasks': 'Week tasks',
		List: 'List',
		Kanban: 'Kanban',
		Todo: 'Todo',
		'Task name': 'Task name',
		'Due date': 'Due date',
		Priority: 'Priority',
		Today: 'Today',
		Tomorrow: 'Tomorrow',
		'On this week': 'On this week',
		'On next week': 'On next week',
		Later: 'Later',
		Completed: 'Completed',
		'Add task...': 'Add task...',
		'Create session': 'Create session',
		Cancel: 'Cancel',
		Start: 'Start',
		Pause: 'Pause',
		'Enter name:': 'Enter name:',
		'Enter duration: (min.):': 'Enter duration: (min.):',
		Color: 'Color',
		Create: 'Create',
		'Total time': 'Total time',
		hours: 'hours',
		minutes: 'minutes',
		'left for sleep': 'left for sleep',
		Security: 'Security',
		Appearance: 'Appearance',
		'With love from': 'With love from',
		'All rights reserved': 'All rights reserved',
		Name: 'Name',
		Mail: 'Mail',
		Password: 'Password',
		'Enter new name': 'Enter new name',
		'Enter new mail': 'Enter new mail',
		'Enter new password': 'Enter new password',
		Save: 'Save',
		'Work interval (min.):': 'Work interval (min.):',
		'Break interval (min.):': 'Break interval (minutes):',
		'Intervals count (max 10):': 'Intervals count (max 10):',
		'Enter work interval:': 'Enter work interval:',
		'Enter break interval:': 'Enter break interval:',
		'Enter intervals count:': 'Enter intervals count:',
		'Dark theme': 'Dark theme',
		Language: 'Language',
		'Add the first time block on the right form':
			'Add the first time block on the right form'
	},
	de: {
		Home: 'Zuhause',
		Tasks: 'Aufgaben',
		Timer: 'Timer',
		'Time blocking': 'Zeitblockierung',
		Settings: 'Einstellungen',
		Statistics: 'Statistiken',
		'Total tasks': 'Gesamtaufgaben',
		'Completed tasks': 'Abgeschlossene Aufgaben',
		'Today tasks': 'Heutige Aufgaben',
		'Week tasks': 'Wochenaufgaben',
		List: 'Liste',
		Kanban: 'Tafel',
		Todo: 'To-do-Liste',
		'Task name': 'Aufgabenname',
		'Due date': 'Fälligkeitsdatum',
		Priority: 'Priorität',
		Today: 'Heute',
		Tomorrow: 'Morgen',
		'On this week': 'In dieser Woche',
		'On next week': 'In der nächsten Woche',
		Later: 'Später',
		Completed: 'Abgeschlossen',
		'Add task...': 'Aufgabe hinzufügen...',
		'Create session': 'Sitzung erstellen',
		Cancel: 'Stornieren',
		Start: 'Starten',
		Pause: 'Pause',
		'Enter name:': 'Name eingeben:',
		'Enter duration: (min.):': 'Dauer eingeben: (min.):',
		Color: 'Farbe',
		Create: 'Erstellen',
		'Total time': 'Gesamtzeit',
		hours: 'Stunden',
		minutes: 'Minuten',
		'left for sleep': 'bleibt zum Schlafen',
		Security: 'Sicherheit',
		Appearance: 'Aussehen',
		'With love from': 'Mit Liebe von',
		'All rights reserved': 'Alle Rechte vorbehalten',
		Name: 'Name',
		Mail: 'Mail',
		Password: 'Passwort',
		'Enter new name': 'Neuen Namen eingeben',
		'Enter new mail': 'Neue E-Mail eingeben',
		'Enter new password': 'Neues Passwort eingeben',
		Save: 'Sparen',
		'Work interval (min.):': 'Arbeitsintervall (min.):',
		'Break interval (min.):': 'Pausenintervall (Minuten):',
		'Intervals count (max 10):': 'Intervallanzahl (max 10):',
		'Enter work interval:': 'Arbeitsintervall eingeben:',
		'Enter break interval:': 'Pausenintervall eingeben:',
		'Enter intervals count:': 'Intervallanzahl eingeben:',
		'Dark theme': 'Dunkles Thema',
		Language: 'Sprache',
		'Add the first time block on the right form':
			'Fügen Sie den ersten Zeitblock im rechten Formular hinzu'
	},
	zh: {
		Home: '家',
		Tasks: '任务',
		Timer: '计时器',
		'Time blocking': '时间阻塞',
		Settings: '设置',
		Statistics: '统计',
		'Total tasks': '总任务',
		'Completed tasks': '已完成的任务',
		'Today tasks': '今天的任务',
		'Week tasks': '本周任务',
		List: '名单',
		Kanban: '董事会',
		Todo: '待办事项清单',
		'Task name': '任务名称',
		'Due date': '到期日',
		Priority: '优先',
		Today: '今天',
		Tomorrow: '明天',
		'On this week': '在这周',
		'On next week': '在下周',
		Later: '后来',
		Completed: '已完成',
		'Add task...': '添加任务...',
		'Create session': '创建会话',
		Cancel: '取消',
		Start: '开始',
		Pause: '暂停',
		'Enter name:': '输入名字:',
		'Enter duration: (min.):': '输入持续时间: (分钟.):',
		Color: '颜色',
		Create: '创建',
		'Total time': '总时间',
		hours: '小时',
		minutes: '分钟',
		'left for sleep': '剩下的睡眠时间',
		Security: '安全',
		Appearance: '外观',
		'With love from': '来自爱',
		'All rights reserved': '保留所有权利',
		Name: '名称',
		Mail: '邮件',
		Password: '密码',
		'Enter new name': '输入新名称',
		'Enter new mail': '输入新邮件',
		'Enter new password': '输入新密码',
		Save: '保存',
		'Work interval (min.):': '工作间隔 (分钟.):',
		'Break interval (min.):': '休息间隔 (分钟):',
		'Intervals count (max 10):': '间隔计数 (最大 10):',
		'Enter work interval:': '输入工作间隔:',
		'Enter break interval:': '输入休息间隔:',
		'Enter intervals count:': '输入间隔计数:',
		'Dark theme': '黑暗主题',
		Language: '语言',
		'Add the first time block on the right form': '在右侧表单中添加第一个时间块'
	}
}
